from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone

from langchain_anthropic import ChatAnthropic
from langchain_anthropic.middleware import AnthropicPromptCachingMiddleware
from langchain.agents import create_agent
from langchain_core.messages import AIMessage
from langgraph.errors import GraphRecursionError
from pydantic import BaseModel

from dp_ops_agent.audit.models import AuditEvent
from dp_ops_agent.audit.sink import AuditSink
from dp_ops_agent.evidence.schema import Diagnosis
from dp_ops_agent.orchestrator.prompts import render_system_prompt
from dp_ops_agent.orchestrator.tool_errors import (
    build_tool_error_middleware,
    build_tool_retry_middleware,
)
from dp_ops_agent.tools.dbt.gateway import DbtArtifactsGateway
from dp_ops_agent.tools.flink.gateway import FlinkMetricsGateway
from dp_ops_agent.tools.kafka.gateway import KafkaMetricsGateway
from dp_ops_agent.tools.lineage.gateway import LineageQueryGateway
from dp_ops_agent.tools.registry import build_tools


class DiagnosisNotSubmittedError(RuntimeError):
    """Raised when the session ends without a call to submit_diagnosis."""


class TokenUsage(BaseModel):
    """Summed over every model reply in a session. input_tokens includes the
    cached portions; cache_read_tokens is what prompt caching saved being
    billed at the full input rate."""

    input_tokens: int = 0
    output_tokens: int = 0
    cache_read_tokens: int = 0
    cache_creation_tokens: int = 0
    model_calls: int = 0


def _total_usage(messages: list) -> TokenUsage:
    usage = TokenUsage()
    for message in messages:
        if not isinstance(message, AIMessage) or not message.usage_metadata:
            continue
        meta = message.usage_metadata
        details = meta.get("input_token_details") or {}
        usage.input_tokens += meta.get("input_tokens", 0)
        usage.output_tokens += meta.get("output_tokens", 0)
        usage.cache_read_tokens += details.get("cache_read", 0) or 0
        usage.cache_creation_tokens += details.get("cache_creation", 0) or 0
        usage.model_calls += 1
    return usage


@dataclass
class DiagnosisRunResult:
    diagnosis: Diagnosis
    session_id: str
    audit_log_path: str | None
    usage: TokenUsage


async def run_diagnosis(
    session_id: str,
    alert_text: str,
    kafka_gateway: KafkaMetricsGateway,
    flink_gateway: FlinkMetricsGateway,
    lineage_gateway: LineageQueryGateway,
    dbt_gateway: DbtArtifactsGateway,
    audit: AuditSink,
    model: str,
) -> DiagnosisRunResult:
    """`session_id` is generated by the caller because it's also used to key
    the AuditSink (e.g. JsonlAuditSink writes to logs/audit/{session_id}.jsonl),
    which must exist before this function's first audit.append() call."""
    audit.append(
        AuditEvent(
            event_type="diagnosis_run_started",
            timestamp=datetime.now(timezone.utc),
            session_id=session_id,
            actor="orchestrator",
            payload={"alert_text": alert_text, "model": model},
        )
    )

    result_holder: dict[str, Diagnosis] = {}
    tools = build_tools(
        kafka_gateway,
        flink_gateway,
        lineage_gateway,
        dbt_gateway,
        audit,
        session_id,
        model,
        result_holder,
    )

    agent = create_agent(
        model=ChatAnthropic(model=model),
        tools=tools,
        system_prompt=render_system_prompt(phase=3),
        # First in the list is outermost: a transport error gets one retry,
        # and only if that also fails does the error middleware turn it into
        # an error ToolMessage (see orchestrator/tool_errors.py).
        middleware=[
            build_tool_error_middleware(audit, session_id),
            build_tool_retry_middleware(),
            # Caches the system prompt, tool definitions, and conversation so
            # far across the session's model calls. It wraps model calls, not
            # tool calls, so its position relative to the two above doesn't
            # matter.
            AnthropicPromptCachingMiddleware(),
        ],
    )

    try:
        # A session that hits the recursion limit raises out of here before
        # its usage is totalled below, so its tokens aren't recorded.
        final_state = await agent.ainvoke(
            {"messages": [{"role": "user", "content": alert_text}]},
            {
                "recursion_limit": 50,
                # Correlates a LangSmith trace back to this session's audit
                # log entries. Tracing itself is opt-in via the LANGSMITH_*
                # env vars (see .env.example) and a no-op otherwise.
                "run_name": f"diagnose-{session_id}",
                "tags": ["phase-3", "kafka", "flink", "lineage", "dbt"],
                "metadata": {"session_id": session_id, "model": model},
            },
        )
    except GraphRecursionError as exc:
        raise DiagnosisNotSubmittedError(
            f"Session {session_id} exceeded the tool-call recursion limit without "
            "calling submit_diagnosis"
        ) from exc

    usage = _total_usage(final_state["messages"])
    audit.append(
        AuditEvent(
            event_type="session_usage",
            timestamp=datetime.now(timezone.utc),
            session_id=session_id,
            actor="orchestrator",
            payload=usage.model_dump(),
        )
    )

    if "diagnosis" not in result_holder:
        raise DiagnosisNotSubmittedError(
            f"Session {session_id} ended without calling submit_diagnosis"
        )

    audit_path = getattr(audit, "path", None)
    return DiagnosisRunResult(
        diagnosis=result_holder["diagnosis"],
        session_id=session_id,
        audit_log_path=str(audit_path) if audit_path else None,
        usage=usage,
    )
